2018-07-11 19:53:34,502 - util.py[DEBUG]: Cloud-init v. 18.2 running 'init-local' at Wed, 11 Jul 2018 19:53:34 +0000. Up 4.41 seconds.
2018-07-11 19:53:34,502 - main.py[DEBUG]: No kernel command line url found.
2018-07-11 19:53:34,502 - main.py[DEBUG]: Closing stdin.
2018-07-11 19:53:34,517 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
2018-07-11 19:53:34,525 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 0:4
2018-07-11 19:53:34,525 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished
2018-07-11 19:53:34,526 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/data/no-net
2018-07-11 19:53:34,526 - handlers.py[DEBUG]: start: init-local/check-cache: attempting to read from cache [check]
2018-07-11 19:53:34,526 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2018-07-11 19:53:34,526 - stages.py[DEBUG]: no cache found
2018-07-11 19:53:34,526 - handlers.py[DEBUG]: finish: init-local/check-cache: SUCCESS: no cache found
2018-07-11 19:53:34,526 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2018-07-11 19:53:34,535 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2018-07-11 19:53:34,536 - __init__.py[DEBUG]: Looking for data source in: ['NoCloud', 'ConfigDrive', 'OpenNebula', 'DigitalOcean', 'Azure', 'AltCloud', 'OVF', 'MAAS', 'GCE', 'OpenStack', 'CloudSigma', 'SmartOS', 'Bigstep', 'Scaleway', 'AliYun', 'Ec2', 'CloudStack', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
2018-07-11 19:53:34,669 - __init__.py[DEBUG]: Searching for local data source in: ['DataSourceNoCloud', 'DataSourceConfigDrive', 'DataSourceOpenNebula', 'DataSourceDigitalOcean', 'DataSourceAzure', 'DataSourceOVF', 'DataSourceCloudSigma', 'DataSourceSmartOS', 'DataSourceEc2Local']
2018-07-11 19:53:34,670 - handlers.py[DEBUG]: start: init-local/search-NoCloud: searching for local data from DataSourceNoCloud
2018-07-11 19:53:34,670 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceNoCloud.DataSourceNoCloud'>
2018-07-11 19:53:34,670 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:34,676 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:34,684 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:34,688 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2018-07-11 19:53:34,688 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2018-07-11 19:53:34,688 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2018-07-11 19:53:34,688 - util.py[DEBUG]: Read 932 bytes from /proc/self/status
2018-07-11 19:53:34,688 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2018-07-11 19:53:34,688 - util.py[DEBUG]: Reading from /sys/class/dmi/id/product_serial (quiet=False)
2018-07-11 19:53:34,688 - util.py[DEBUG]: Read 37 bytes from /sys/class/dmi/id/product_serial
2018-07-11 19:53:34,688 - util.py[DEBUG]: dmi data /sys/class/dmi/id/product_serial returned ec281547-f234-9d90-c02d-ab1d79188ba3
2018-07-11 19:53:34,689 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/user-data (quiet=False)
2018-07-11 19:53:34,689 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/meta-data (quiet=False)
2018-07-11 19:53:34,689 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/vendor-data (quiet=False)
2018-07-11 19:53:34,689 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/network-config (quiet=False)
2018-07-11 19:53:34,689 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/user-data (quiet=False)
2018-07-11 19:53:34,689 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/meta-data (quiet=False)
2018-07-11 19:53:34,689 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/vendor-data (quiet=False)
2018-07-11 19:53:34,689 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/network-config (quiet=False)
2018-07-11 19:53:34,689 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/sr0'] with allowed return codes [0, 2] (shell=False, capture=True)
2018-07-11 19:53:34,700 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/sr1'] with allowed return codes [0, 2] (shell=False, capture=True)
2018-07-11 19:53:34,703 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=vfat', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2018-07-11 19:53:34,762 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=iso9660', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2018-07-11 19:53:34,812 - util.py[DEBUG]: Running command ['blkid', '-tLABEL=cidata', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2018-07-11 19:53:34,868 - handlers.py[DEBUG]: finish: init-local/search-NoCloud: SUCCESS: no local data found from DataSourceNoCloud
2018-07-11 19:53:34,869 - handlers.py[DEBUG]: start: init-local/search-ConfigDrive: searching for local data from DataSourceConfigDrive
2018-07-11 19:53:34,869 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceConfigDrive.DataSourceConfigDrive'>
2018-07-11 19:53:34,869 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/sr0'] with allowed return codes [0, 2] (shell=False, capture=True)
2018-07-11 19:53:34,875 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/sr1'] with allowed return codes [0, 2] (shell=False, capture=True)
2018-07-11 19:53:34,879 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/cd0'] with allowed return codes [0, 2] (shell=False, capture=True)
2018-07-11 19:53:34,888 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/cd1'] with allowed return codes [0, 2] (shell=False, capture=True)
2018-07-11 19:53:34,893 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=vfat', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2018-07-11 19:53:34,944 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=iso9660', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2018-07-11 19:53:34,995 - util.py[DEBUG]: Running command ['blkid', '-tLABEL=config-2', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2018-07-11 19:53:35,043 - util.py[DEBUG]: Running command ['blkid', '-tLABEL=CONFIG-2', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2018-07-11 19:53:35,093 - DataSourceConfigDrive.py[DEBUG]: devices=[] dslist=['NoCloud', 'ConfigDrive', 'OpenNebula', 'DigitalOcean', 'Azure', 'AltCloud', 'OVF', 'MAAS', 'GCE', 'OpenStack', 'CloudSigma', 'SmartOS', 'Bigstep', 'Scaleway', 'AliYun', 'Ec2', 'CloudStack', 'None']
2018-07-11 19:53:35,093 - handlers.py[DEBUG]: finish: init-local/search-ConfigDrive: SUCCESS: no local data found from DataSourceConfigDrive
2018-07-11 19:53:35,093 - handlers.py[DEBUG]: start: init-local/search-OpenNebula: searching for local data from DataSourceOpenNebula
2018-07-11 19:53:35,094 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceOpenNebula.DataSourceOpenNebula'>
2018-07-11 19:53:35,094 - util.py[DEBUG]: Running command ['blkid', '-tLABEL=CONTEXT', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2018-07-11 19:53:35,144 - util.py[DEBUG]: Running command ['blkid', '-tLABEL=CDROM', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2018-07-11 19:53:35,196 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=iso9660', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2018-07-11 19:53:35,248 - handlers.py[DEBUG]: finish: init-local/search-OpenNebula: SUCCESS: no local data found from DataSourceOpenNebula
2018-07-11 19:53:35,249 - handlers.py[DEBUG]: start: init-local/search-DigitalOcean: searching for local data from DataSourceDigitalOcean
2018-07-11 19:53:35,249 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceDigitalOcean.DataSourceDigitalOcean'>
2018-07-11 19:53:35,249 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,257 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,258 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,262 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2018-07-11 19:53:35,262 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2018-07-11 19:53:35,262 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2018-07-11 19:53:35,262 - util.py[DEBUG]: Read 932 bytes from /proc/self/status
2018-07-11 19:53:35,263 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/sys_vendor
2018-07-11 19:53:35,263 - util.py[DEBUG]: Reading from /sys/class/dmi/id/sys_vendor (quiet=False)
2018-07-11 19:53:35,263 - util.py[DEBUG]: Read 4 bytes from /sys/class/dmi/id/sys_vendor
2018-07-11 19:53:35,263 - util.py[DEBUG]: dmi data /sys/class/dmi/id/sys_vendor returned Xen
2018-07-11 19:53:35,267 - handlers.py[DEBUG]: finish: init-local/search-DigitalOcean: SUCCESS: no local data found from DataSourceDigitalOcean
2018-07-11 19:53:35,268 - handlers.py[DEBUG]: start: init-local/search-Azure: searching for local data from DataSourceAzure
2018-07-11 19:53:35,268 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceAzure.DataSourceAzure'>
2018-07-11 19:53:35,268 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,279 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,280 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,282 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2018-07-11 19:53:35,282 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2018-07-11 19:53:35,282 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2018-07-11 19:53:35,282 - util.py[DEBUG]: Read 932 bytes from /proc/self/status
2018-07-11 19:53:35,282 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
2018-07-11 19:53:35,282 - util.py[DEBUG]: Reading from /sys/class/dmi/id/chassis_asset_tag (quiet=False)
2018-07-11 19:53:35,282 - util.py[DEBUG]: Read 1 bytes from /sys/class/dmi/id/chassis_asset_tag
2018-07-11 19:53:35,282 - util.py[DEBUG]: dmi data /sys/class/dmi/id/chassis_asset_tag returned 
2018-07-11 19:53:35,282 - DataSourceAzure.py[DEBUG]: Non-Azure DMI asset tag '' discovered.
2018-07-11 19:53:35,283 - handlers.py[DEBUG]: finish: init-local/search-Azure: SUCCESS: no local data found from DataSourceAzure
2018-07-11 19:53:35,283 - handlers.py[DEBUG]: start: init-local/search-OVF: searching for local data from DataSourceOVF
2018-07-11 19:53:35,283 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceOVF.DataSourceOVF'>
2018-07-11 19:53:35,291 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,293 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,295 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,300 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2018-07-11 19:53:35,300 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2018-07-11 19:53:35,300 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2018-07-11 19:53:35,300 - util.py[DEBUG]: Read 932 bytes from /proc/self/status
2018-07-11 19:53:35,301 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_name
2018-07-11 19:53:35,301 - util.py[DEBUG]: Reading from /sys/class/dmi/id/product_name (quiet=False)
2018-07-11 19:53:35,301 - util.py[DEBUG]: Read 9 bytes from /sys/class/dmi/id/product_name
2018-07-11 19:53:35,301 - util.py[DEBUG]: dmi data /sys/class/dmi/id/product_name returned HVM domU
2018-07-11 19:53:35,301 - util.py[DEBUG]: Reading from /proc/mounts (quiet=False)
2018-07-11 19:53:35,301 - util.py[DEBUG]: Read 1988 bytes from /proc/mounts
2018-07-11 19:53:35,301 - util.py[DEBUG]: Fetched {'hugetlbfs': {'opts': 'rw,relatime', 'mountpoint': '/dev/hugepages', 'fstype': 'hugetlbfs'}, 'devpts': {'opts': 'rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000', 'mountpoint': '/dev/pts', 'fstype': 'devpts'}, 'debugfs': {'opts': 'rw,relatime', 'mountpoint': '/sys/kernel/debug', 'fstype': 'debugfs'}, 'udev': {'opts': 'rw,nosuid,relatime,size=1016260k,nr_inodes=254065,mode=755', 'mountpoint': '/dev', 'fstype': 'devtmpfs'}, 'securityfs': {'opts': 'rw,nosuid,nodev,noexec,relatime', 'mountpoint': '/sys/kernel/security', 'fstype': 'securityfs'}, 'proc': {'opts': 'rw,nosuid,nodev,noexec,relatime', 'mountpoint': '/proc', 'fstype': 'proc'}, 'tmpfs': {'opts': 'ro,nosuid,nodev,noexec,mode=755', 'mountpoint': '/sys/fs/cgroup', 'fstype': 'tmpfs'}, 'cgroup': {'opts': 'rw,nosuid,nodev,noexec,relatime,freezer', 'mountpoint': '/sys/fs/cgroup/freezer', 'fstype': 'cgroup'}, 'systemd-1': {'opts': 'rw,relatime,fd=25,pgrp=1,timeout=0,minproto=5,maxproto=5,direct', 'mountpoint': '/proc/sys/fs/binfmt_misc', 'fstype': 'autofs'}, 'pstore': {'opts': 'rw,nosuid,nodev,noexec,relatime', 'mountpoint': '/sys/fs/pstore', 'fstype': 'pstore'}, 'mqueue': {'opts': 'rw,relatime', 'mountpoint': '/dev/mqueue', 'fstype': 'mqueue'}, 'fusectl': {'opts': 'rw,relatime', 'mountpoint': '/sys/fs/fuse/connections', 'fstype': 'fusectl'}, '/dev/xvda1': {'opts': 'rw,relatime,discard,data=ordered', 'mountpoint': '/', 'fstype': 'ext4'}, 'sysfs': {'opts': 'rw,nosuid,nodev,noexec,relatime', 'mountpoint': '/sys', 'fstype': 'sysfs'}} mounts from proc
2018-07-11 19:53:35,301 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=iso9660', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2018-07-11 19:53:35,355 - handlers.py[DEBUG]: finish: init-local/search-OVF: SUCCESS: no local data found from DataSourceOVF
2018-07-11 19:53:35,356 - handlers.py[DEBUG]: start: init-local/search-CloudSigma: searching for local data from DataSourceCloudSigma
2018-07-11 19:53:35,356 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceCloudSigma.DataSourceCloudSigma'>
2018-07-11 19:53:35,356 - DataSourceCloudSigma.py[DEBUG]: determining hypervisor product name via dmi data
2018-07-11 19:53:35,356 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,358 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,366 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,372 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2018-07-11 19:53:35,372 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2018-07-11 19:53:35,372 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2018-07-11 19:53:35,372 - util.py[DEBUG]: Read 932 bytes from /proc/self/status
2018-07-11 19:53:35,372 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_name
2018-07-11 19:53:35,372 - util.py[DEBUG]: Reading from /sys/class/dmi/id/product_name (quiet=False)
2018-07-11 19:53:35,372 - util.py[DEBUG]: Read 9 bytes from /sys/class/dmi/id/product_name
2018-07-11 19:53:35,372 - util.py[DEBUG]: dmi data /sys/class/dmi/id/product_name returned HVM domU
2018-07-11 19:53:35,372 - DataSourceCloudSigma.py[DEBUG]: detected hypervisor as HVM domU
2018-07-11 19:53:35,373 - handlers.py[DEBUG]: finish: init-local/search-CloudSigma: SUCCESS: no local data found from DataSourceCloudSigma
2018-07-11 19:53:35,373 - handlers.py[DEBUG]: start: init-local/search-SmartOS: searching for local data from DataSourceSmartOS
2018-07-11 19:53:35,373 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceSmartOS.DataSourceSmartOS'>
2018-07-11 19:53:35,373 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,389 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,398 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,399 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2018-07-11 19:53:35,400 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2018-07-11 19:53:35,400 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2018-07-11 19:53:35,400 - util.py[DEBUG]: Read 932 bytes from /proc/self/status
2018-07-11 19:53:35,400 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_name
2018-07-11 19:53:35,400 - util.py[DEBUG]: Reading from /sys/class/dmi/id/product_name (quiet=False)
2018-07-11 19:53:35,400 - util.py[DEBUG]: Read 9 bytes from /sys/class/dmi/id/product_name
2018-07-11 19:53:35,400 - util.py[DEBUG]: dmi data /sys/class/dmi/id/product_name returned HVM domU
2018-07-11 19:53:35,400 - DataSourceSmartOS.py[DEBUG]: Not running on smartos
2018-07-11 19:53:35,400 - handlers.py[DEBUG]: finish: init-local/search-SmartOS: SUCCESS: no local data found from DataSourceSmartOS
2018-07-11 19:53:35,400 - handlers.py[DEBUG]: start: init-local/search-Ec2Local: searching for local data from DataSourceEc2Local
2018-07-11 19:53:35,401 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2Local'>
2018-07-11 19:53:35,401 - util.py[DEBUG]: Reading from /sys/hypervisor/uuid (quiet=False)
2018-07-11 19:53:35,407 - util.py[DEBUG]: Read 37 bytes from /sys/hypervisor/uuid
2018-07-11 19:53:35,407 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,415 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,417 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,419 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2018-07-11 19:53:35,420 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2018-07-11 19:53:35,420 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2018-07-11 19:53:35,420 - util.py[DEBUG]: Read 932 bytes from /proc/self/status
2018-07-11 19:53:35,420 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2018-07-11 19:53:35,420 - util.py[DEBUG]: Reading from /sys/class/dmi/id/product_serial (quiet=False)
2018-07-11 19:53:35,420 - util.py[DEBUG]: Read 37 bytes from /sys/class/dmi/id/product_serial
2018-07-11 19:53:35,420 - util.py[DEBUG]: dmi data /sys/class/dmi/id/product_serial returned ec281547-f234-9d90-c02d-ab1d79188ba3
2018-07-11 19:53:35,420 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/ec2/meta-data (quiet=False)
2018-07-11 19:53:35,425 - DataSourceEc2.py[DEBUG]: strict_mode: warn, cloud_platform=AWS
2018-07-11 19:53:35,425 - util.py[DEBUG]: Reading from /sys/class/net/eth0/carrier (quiet=False)
2018-07-11 19:53:35,425 - util.py[DEBUG]: Reading from /sys/class/net/eth0/dormant (quiet=False)
2018-07-11 19:53:35,425 - util.py[DEBUG]: Reading from /sys/class/net/eth0/operstate (quiet=False)
2018-07-11 19:53:35,426 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/eth0/operstate
2018-07-11 19:53:35,426 - util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
2018-07-11 19:53:35,426 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
2018-07-11 19:53:35,426 - dhcp.py[DEBUG]: Performing a dhcp discovery on eth0
2018-07-11 19:53:35,426 - util.py[DEBUG]: Copying /sbin/dhclient to /var/tmp/cloud-init/cloud-init-dhcp-11oxj5vv/dhclient
2018-07-11 19:53:35,434 - util.py[DEBUG]: Running command ['ip', 'link', 'set', 'dev', 'eth0', 'up'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,445 - util.py[DEBUG]: Running command ['/var/tmp/cloud-init/cloud-init-dhcp-11oxj5vv/dhclient', '-1', '-v', '-lf', '/var/tmp/cloud-init/cloud-init-dhcp-11oxj5vv/dhcp.leases', '-pf', '/var/tmp/cloud-init/cloud-init-dhcp-11oxj5vv/dhclient.pid', 'eth0', '-sf', '/bin/true'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,471 - util.py[DEBUG]: All files appeared after 0 seconds: ['/var/tmp/cloud-init/cloud-init-dhcp-11oxj5vv/dhclient.pid', '/var/tmp/cloud-init/cloud-init-dhcp-11oxj5vv/dhcp.leases']
2018-07-11 19:53:35,471 - util.py[DEBUG]: Reading from /var/tmp/cloud-init/cloud-init-dhcp-11oxj5vv/dhclient.pid (quiet=False)
2018-07-11 19:53:35,471 - util.py[DEBUG]: Read 4 bytes from /var/tmp/cloud-init/cloud-init-dhcp-11oxj5vv/dhclient.pid
2018-07-11 19:53:35,471 - util.py[DEBUG]: Reading from /var/tmp/cloud-init/cloud-init-dhcp-11oxj5vv/dhcp.leases (quiet=False)
2018-07-11 19:53:35,472 - util.py[DEBUG]: Read 516 bytes from /var/tmp/cloud-init/cloud-init-dhcp-11oxj5vv/dhcp.leases
2018-07-11 19:53:35,472 - dhcp.py[DEBUG]: Received dhcp lease on eth0 for 172.31.29.193/255.255.240.0
2018-07-11 19:53:35,472 - __init__.py[DEBUG]: Attempting setup of ephemeral network on eth0 with 172.31.29.193/20 brd 172.31.31.255
2018-07-11 19:53:35,472 - util.py[DEBUG]: Running command ['ip', '-family', 'inet', 'addr', 'add', '172.31.29.193/20', 'broadcast', '172.31.31.255', 'dev', 'eth0'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,479 - util.py[DEBUG]: Running command ['ip', '-family', 'inet', 'link', 'set', 'dev', 'eth0', 'up'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,487 - util.py[DEBUG]: Running command ['ip', 'route', 'show', '0.0.0.0/0'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,491 - util.py[DEBUG]: Running command ['ip', '-4', 'route', 'add', 'default', 'via', '172.31.16.1', 'dev', 'eth0'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,506 - DataSourceEc2.py[DEBUG]: Removed the following from metadata urls: ['http://instance-data.:8773']
2018-07-11 19:53:35,507 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254/2009-04-04/meta-data/instance-id' with {'url': 'http://169.254.169.254/2009-04-04/meta-data/instance-id', 'timeout': 50.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,523 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2009-04-04/meta-data/instance-id (200, 19b) after 1 attempts
2018-07-11 19:53:35,523 - DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254'
2018-07-11 19:53:35,523 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254/2016-09-02/meta-data/instance-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-id', 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,532 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-id (200, 19b) after 1 attempts
2018-07-11 19:53:35,532 - DataSourceEc2.py[DEBUG]: Found preferred metadata version 2016-09-02
2018-07-11 19:53:35,533 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/user-data' with {'url': 'http://169.254.169.254/2016-09-02/user-data', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,537 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,544 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ (200, 263b) after 1 attempts
2018-07-11 19:53:35,544 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,552 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ (200, 13b) after 1 attempts
2018-07-11 19:53:35,552 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/root', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,561 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
2018-07-11 19:53:35,562 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ami', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,566 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ami (200, 9b) after 1 attempts
2018-07-11 19:53:35,567 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ebs2' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ebs2', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,574 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ebs2 (200, 3b) after 1 attempts
2018-07-11 19:53:35,574 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/metrics/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/metrics/', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,583 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/metrics/ (200, 7b) after 1 attempts
2018-07-11 19:53:35,583 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/metrics/vhostmd', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,585 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
2018-07-11 19:53:35,586 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,591 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/ (200, 11b) after 1 attempts
2018-07-11 19:53:35,592 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,594 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/ (200, 5b) after 1 attempts
2018-07-11 19:53:35,594 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,596 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
2018-07-11 19:53:35,596 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,600 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/ (200, 230b) after 1 attempts
2018-07-11 19:53:35,600 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/ipv4-associations/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/ipv4-associations/', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,604 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/ipv4-associations/ (200, 13b) after 1 attempts
2018-07-11 19:53:35,604 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/ipv4-associations/35.153.178.97' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/ipv4-associations/35.153.178.97', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,608 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/ipv4-associations/35.153.178.97 (200, 13b) after 1 attempts
2018-07-11 19:53:35,608 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/interface-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/interface-id', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,610 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/interface-id (200, 12b) after 1 attempts
2018-07-11 19:53:35,610 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/subnet-ipv4-cidr-block', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,616 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/subnet-ipv4-cidr-block (200, 14b) after 1 attempts
2018-07-11 19:53:35,616 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/subnet-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/subnet-id', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,618 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/subnet-id (200, 15b) after 1 attempts
2018-07-11 19:53:35,618 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/vpc-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/vpc-id', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,624 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/vpc-id (200, 12b) after 1 attempts
2018-07-11 19:53:35,624 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/security-group-ids' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/security-group-ids', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,626 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/security-group-ids (200, 11b) after 1 attempts
2018-07-11 19:53:35,626 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/public-hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/public-hostname', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,632 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/public-hostname (200, 41b) after 1 attempts
2018-07-11 19:53:35,632 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/public-ipv4s' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/public-ipv4s', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,634 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/public-ipv4s (200, 13b) after 1 attempts
2018-07-11 19:53:35,634 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/device-number' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/device-number', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,640 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/device-number (200, 1b) after 1 attempts
2018-07-11 19:53:35,640 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/mac' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/mac', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,642 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/mac (200, 17b) after 1 attempts
2018-07-11 19:53:35,642 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/local-hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/local-hostname', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,648 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/local-hostname (200, 29b) after 1 attempts
2018-07-11 19:53:35,648 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/vpc-ipv4-cidr-block', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,653 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/vpc-ipv4-cidr-block (200, 13b) after 1 attempts
2018-07-11 19:53:35,653 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/vpc-ipv4-cidr-blocks', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,655 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/vpc-ipv4-cidr-blocks (200, 13b) after 1 attempts
2018-07-11 19:53:35,656 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/owner-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/owner-id', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,660 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/owner-id (200, 12b) after 1 attempts
2018-07-11 19:53:35,660 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/security-groups' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/security-groups', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,665 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/security-groups (200, 8b) after 1 attempts
2018-07-11 19:53:35,665 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/local-ipv4s' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/local-ipv4s', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,672 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0e:15:bc:04:d8:dc/local-ipv4s (200, 13b) after 1 attempts
2018-07-11 19:53:35,672 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/placement/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/placement/', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,674 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/placement/ (200, 17b) after 1 attempts
2018-07-11 19:53:35,674 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/placement/availability-zone', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,680 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/placement/availability-zone (200, 10b) after 1 attempts
2018-07-11 19:53:35,680 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-keys/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/public-keys/', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,682 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-keys/ (200, 11b) after 1 attempts
2018-07-11 19:53:35,682 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-keys/0/openssh-key' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/public-keys/0/openssh-key', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,688 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-keys/0/openssh-key (200, 391b) after 1 attempts
2018-07-11 19:53:35,688 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/services/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/services/', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,690 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/services/ (200, 16b) after 1 attempts
2018-07-11 19:53:35,690 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/services/partition' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/services/partition', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,696 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/services/partition (200, 3b) after 1 attempts
2018-07-11 19:53:35,696 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/services/domain' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/services/domain', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,698 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/services/domain (200, 13b) after 1 attempts
2018-07-11 19:53:35,698 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/ami-manifest-path', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,704 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ami-manifest-path (200, 9b) after 1 attempts
2018-07-11 19:53:35,704 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/local-ipv4' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/local-ipv4', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,706 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/local-ipv4 (200, 13b) after 1 attempts
2018-07-11 19:53:35,706 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/hostname', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,712 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/hostname (200, 29b) after 1 attempts
2018-07-11 19:53:35,712 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/instance-action' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-action', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,714 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-action (200, 4b) after 1 attempts
2018-07-11 19:53:35,714 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/instance-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-id', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,720 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-id (200, 19b) after 1 attempts
2018-07-11 19:53:35,720 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/ami-launch-index', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,722 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ami-launch-index (200, 1b) after 1 attempts
2018-07-11 19:53:35,722 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/profile' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/profile', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,728 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/profile (200, 11b) after 1 attempts
2018-07-11 19:53:35,728 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/public-hostname', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,730 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-hostname (200, 41b) after 1 attempts
2018-07-11 19:53:35,731 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-ipv4' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/public-ipv4', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,736 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-ipv4 (200, 13b) after 1 attempts
2018-07-11 19:53:35,736 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/mac' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/mac', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,738 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/mac (200, 17b) after 1 attempts
2018-07-11 19:53:35,738 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/instance-type' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-type', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,744 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-type (200, 8b) after 1 attempts
2018-07-11 19:53:35,744 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/ami-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/ami-id', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,746 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ami-id (200, 12b) after 1 attempts
2018-07-11 19:53:35,746 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/local-hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/local-hostname', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,752 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/local-hostname (200, 29b) after 1 attempts
2018-07-11 19:53:35,752 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/reservation-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/reservation-id', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,754 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/reservation-id (200, 19b) after 1 attempts
2018-07-11 19:53:35,754 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/security-groups' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/security-groups', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,760 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/security-groups (200, 8b) after 1 attempts
2018-07-11 19:53:35,760 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,763 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity (200, 33b) after 1 attempts
2018-07-11 19:53:35,764 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/signature', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,772 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/signature (200, 174b) after 1 attempts
2018-07-11 19:53:35,772 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/rsa2048', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,779 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/rsa2048 (200, 1422b) after 1 attempts
2018-07-11 19:53:35,779 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/pkcs7', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,782 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/pkcs7 (200, 1106b) after 1 attempts
2018-07-11 19:53:35,782 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/document', 'timeout': 5.0, 'allow_redirects': True, 'headers': {'User-Agent': 'Cloud-Init/18.2'}, 'method': 'GET'} configuration
2018-07-11 19:53:35,785 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/document (200, 468b) after 1 attempts
2018-07-11 19:53:35,786 - util.py[DEBUG]: Crawl of metadata service took 0.288 seconds
2018-07-11 19:53:35,786 - util.py[DEBUG]: Running command ['ip', '-4', 'route', 'del', 'default', 'dev', 'eth0'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,788 - util.py[DEBUG]: Running command ['ip', '-family', 'inet', 'link', 'set', 'dev', 'eth0', 'down'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,790 - util.py[DEBUG]: Running command ['ip', '-family', 'inet', 'addr', 'del', '172.31.29.193/20', 'dev', 'eth0'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,793 - handlers.py[DEBUG]: finish: init-local/search-Ec2Local: SUCCESS: found local data from DataSourceEc2Local
2018-07-11 19:53:35,793 - stages.py[INFO]: Loaded datasource DataSourceEc2Local - DataSourceEc2Local
2018-07-11 19:53:35,793 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2018-07-11 19:53:35,794 - util.py[DEBUG]: Read 3101 bytes from /etc/cloud/cloud.cfg
2018-07-11 19:53:35,794 - util.py[DEBUG]: Attempting to load yaml from string of length 3101 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:35,807 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2018-07-11 19:53:35,807 - util.py[DEBUG]: Read 238 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2018-07-11 19:53:35,807 - util.py[DEBUG]: Attempting to load yaml from string of length 238 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:35,809 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2018-07-11 19:53:35,809 - util.py[DEBUG]: Read 2057 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2018-07-11 19:53:35,809 - util.py[DEBUG]: Attempting to load yaml from string of length 2057 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:35,813 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2018-07-11 19:53:35,813 - util.py[DEBUG]: Read 44 bytes from /run/cloud-init/cloud.cfg
2018-07-11 19:53:35,813 - util.py[DEBUG]: Attempting to load yaml from string of length 44 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:35,814 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:35,814 - util.py[DEBUG]: loaded blob returned None, returning default.
2018-07-11 19:53:35,814 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2018-07-11 19:53:35,814 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-0468a2b9718fc5626'
2018-07-11 19:53:35,816 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-0468a2b9718fc5626/datasource (quiet=False)
2018-07-11 19:53:35,816 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/datasource - wb: [644] 39 bytes
2018-07-11 19:53:35,816 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 39 bytes
2018-07-11 19:53:35,817 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2018-07-11 19:53:35,817 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
2018-07-11 19:53:35,817 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2018-07-11 19:53:35,817 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2018-07-11 19:53:35,817 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
2018-07-11 19:53:35,818 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 8365 bytes
2018-07-11 19:53:35,819 - main.py[DEBUG]: [local] init will now be targeting instance id: i-0468a2b9718fc5626. new=True
2018-07-11 19:53:35,819 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2018-07-11 19:53:35,819 - util.py[DEBUG]: Read 3101 bytes from /etc/cloud/cloud.cfg
2018-07-11 19:53:35,819 - util.py[DEBUG]: Attempting to load yaml from string of length 3101 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:35,831 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2018-07-11 19:53:35,832 - util.py[DEBUG]: Read 238 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2018-07-11 19:53:35,832 - util.py[DEBUG]: Attempting to load yaml from string of length 238 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:35,833 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2018-07-11 19:53:35,833 - util.py[DEBUG]: Read 2057 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2018-07-11 19:53:35,833 - util.py[DEBUG]: Attempting to load yaml from string of length 2057 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:35,838 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2018-07-11 19:53:35,838 - util.py[DEBUG]: Read 44 bytes from /run/cloud-init/cloud.cfg
2018-07-11 19:53:35,838 - util.py[DEBUG]: Attempting to load yaml from string of length 44 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:35,838 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:35,838 - util.py[DEBUG]: loaded blob returned None, returning default.
2018-07-11 19:53:35,840 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2018-07-11 19:53:35,840 - cc_set_hostname.py[DEBUG]: Setting the hostname to ip-172-31-29-193.ec2.internal (ip-172-31-29-193)
2018-07-11 19:53:35,840 - util.py[DEBUG]: Reading from /etc/hostname (quiet=False)
2018-07-11 19:53:35,840 - util.py[DEBUG]: Read 7 bytes from /etc/hostname
2018-07-11 19:53:35,841 - util.py[DEBUG]: Writing to /etc/hostname - wb: [644] 17 bytes
2018-07-11 19:53:35,841 - __init__.py[DEBUG]: Non-persistently setting the system hostname to ip-172-31-29-193
2018-07-11 19:53:35,841 - util.py[DEBUG]: Running command ['hostname', 'ip-172-31-29-193'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,845 - util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
2018-07-11 19:53:35,845 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
2018-07-11 19:53:35,845 - stages.py[DEBUG]: applying net config names for {'config': [{'type': 'physical', 'subnets': [{'type': 'dhcp4'}], 'mac_address': '0e:15:bc:04:d8:dc', 'name': 'eth0'}], 'version': 1}
2018-07-11 19:53:35,845 - util.py[DEBUG]: Reading from /sys/class/net/eth0/device/device (quiet=False)
2018-07-11 19:53:35,846 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2018-07-11 19:53:35,846 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2018-07-11 19:53:35,846 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2018-07-11 19:53:35,846 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2018-07-11 19:53:35,846 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2018-07-11 19:53:35,846 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2018-07-11 19:53:35,846 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2018-07-11 19:53:35,846 - util.py[DEBUG]: Reading from /sys/class/net/eth0/addr_assign_type (quiet=False)
2018-07-11 19:53:35,846 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/eth0/addr_assign_type
2018-07-11 19:53:35,846 - util.py[DEBUG]: Reading from /sys/class/net/eth0/uevent (quiet=False)
2018-07-11 19:53:35,846 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/eth0/uevent
2018-07-11 19:53:35,846 - util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
2018-07-11 19:53:35,846 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
2018-07-11 19:53:35,847 - util.py[DEBUG]: Reading from /sys/class/net/eth0/device/device (quiet=False)
2018-07-11 19:53:35,847 - util.py[DEBUG]: Reading from /sys/class/net/lo/operstate (quiet=False)
2018-07-11 19:53:35,847 - util.py[DEBUG]: Read 8 bytes from /sys/class/net/lo/operstate
2018-07-11 19:53:35,847 - util.py[DEBUG]: Reading from /sys/class/net/eth0/operstate (quiet=False)
2018-07-11 19:53:35,847 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/eth0/operstate
2018-07-11 19:53:35,847 - util.py[DEBUG]: Running command ['ip', '-6', 'addr', 'show', 'permanent', 'scope', 'global'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,851 - util.py[DEBUG]: Running command ['ip', '-4', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:35,853 - __init__.py[DEBUG]: no work necessary for renaming of [['0e:15:bc:04:d8:dc', 'eth0', 'vif', None]]
2018-07-11 19:53:35,853 - stages.py[INFO]: Applying network configuration from ds bringup=False: {'config': [{'type': 'physical', 'subnets': [{'type': 'dhcp4'}], 'mac_address': '0e:15:bc:04:d8:dc', 'name': 'eth0'}], 'version': 1}
2018-07-11 19:53:35,853 - __init__.py[DEBUG]: Selected renderer 'eni' from priority list: None
2018-07-11 19:53:35,856 - util.py[DEBUG]: Writing to /etc/network/interfaces.d/50-cloud-init.cfg - wb: [644] 367 bytes
2018-07-11 19:53:35,856 - util.py[DEBUG]: Writing to /etc/udev/rules.d/70-persistent-net.rules - wb: [644] 96 bytes
2018-07-11 19:53:35,857 - main.py[DEBUG]: [local] Exiting. datasource DataSourceEc2Local not in local mode.
2018-07-11 19:53:35,860 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2018-07-11 19:53:35,860 - util.py[DEBUG]: Read 10 bytes from /proc/uptime
2018-07-11 19:53:35,860 - util.py[DEBUG]: cloud-init mode 'init' took 1.462 seconds (1.46)
2018-07-11 19:53:35,860 - handlers.py[DEBUG]: finish: init-local: SUCCESS: searching for local datasources
2018-07-11 19:53:36,381 - util.py[DEBUG]: Cloud-init v. 18.2 running 'init' at Wed, 11 Jul 2018 19:53:36 +0000. Up 6.34 seconds.
2018-07-11 19:53:36,382 - main.py[DEBUG]: No kernel command line url found.
2018-07-11 19:53:36,382 - main.py[DEBUG]: Closing stdin.
2018-07-11 19:53:36,384 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
2018-07-11 19:53:36,385 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 0:4
2018-07-11 19:53:36,385 - util.py[DEBUG]: Running command ['ifconfig', '-a'] with allowed return codes [0, 1] (shell=False, capture=True)
2018-07-11 19:53:36,389 - util.py[DEBUG]: Running command ['netstat', '-rn'] with allowed return codes [0, 1] (shell=False, capture=True)
2018-07-11 19:53:36,393 - util.py[DEBUG]: Running command ['netstat', '-A', 'inet6', '-n'] with allowed return codes [0, 1] (shell=False, capture=True)
2018-07-11 19:53:36,394 - main.py[DEBUG]: Checking to see if files that we need already exist from a previous run that would allow us to stop early.
2018-07-11 19:53:36,395 - main.py[DEBUG]: Execution continuing, no previous run detected that would allow us to stop early.
2018-07-11 19:53:36,395 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2018-07-11 19:53:36,395 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2018-07-11 19:53:36,395 - util.py[DEBUG]: Read 8365 bytes from /var/lib/cloud/instance/obj.pkl
2018-07-11 19:53:36,398 - util.py[DEBUG]: Reading from /run/cloud-init/.instance-id (quiet=False)
2018-07-11 19:53:36,398 - util.py[DEBUG]: Read 20 bytes from /run/cloud-init/.instance-id
2018-07-11 19:53:36,398 - stages.py[DEBUG]: restored from cache with run check: DataSourceEc2Local
2018-07-11 19:53:36,398 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: restored from cache with run check: DataSourceEc2Local
2018-07-11 19:53:36,399 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2018-07-11 19:53:36,399 - util.py[DEBUG]: Read 3101 bytes from /etc/cloud/cloud.cfg
2018-07-11 19:53:36,399 - util.py[DEBUG]: Attempting to load yaml from string of length 3101 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:36,412 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2018-07-11 19:53:36,412 - util.py[DEBUG]: Read 238 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2018-07-11 19:53:36,413 - util.py[DEBUG]: Attempting to load yaml from string of length 238 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:36,414 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2018-07-11 19:53:36,414 - util.py[DEBUG]: Read 2057 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2018-07-11 19:53:36,414 - util.py[DEBUG]: Attempting to load yaml from string of length 2057 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:36,418 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2018-07-11 19:53:36,418 - util.py[DEBUG]: Read 44 bytes from /run/cloud-init/cloud.cfg
2018-07-11 19:53:36,419 - util.py[DEBUG]: Attempting to load yaml from string of length 44 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:36,419 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:36,419 - util.py[DEBUG]: loaded blob returned None, returning default.
2018-07-11 19:53:36,420 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2018-07-11 19:53:36,420 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-0468a2b9718fc5626'
2018-07-11 19:53:36,421 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-0468a2b9718fc5626/datasource (quiet=False)
2018-07-11 19:53:36,421 - util.py[DEBUG]: Read 39 bytes from /var/lib/cloud/instances/i-0468a2b9718fc5626/datasource
2018-07-11 19:53:36,421 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/datasource - wb: [644] 39 bytes
2018-07-11 19:53:36,421 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 39 bytes
2018-07-11 19:53:36,422 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2018-07-11 19:53:36,422 - util.py[DEBUG]: Read 20 bytes from /var/lib/cloud/data/instance-id
2018-07-11 19:53:36,422 - stages.py[DEBUG]: previous iid found to be i-0468a2b9718fc5626
2018-07-11 19:53:36,422 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2018-07-11 19:53:36,422 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2018-07-11 19:53:36,423 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 20 bytes
2018-07-11 19:53:36,424 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 8441 bytes
2018-07-11 19:53:36,424 - main.py[DEBUG]: [net] init will now be targeting instance id: i-0468a2b9718fc5626. new=False
2018-07-11 19:53:36,424 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2018-07-11 19:53:36,424 - util.py[DEBUG]: Read 3101 bytes from /etc/cloud/cloud.cfg
2018-07-11 19:53:36,425 - util.py[DEBUG]: Attempting to load yaml from string of length 3101 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:36,437 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2018-07-11 19:53:36,437 - util.py[DEBUG]: Read 238 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2018-07-11 19:53:36,437 - util.py[DEBUG]: Attempting to load yaml from string of length 238 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:36,439 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2018-07-11 19:53:36,439 - util.py[DEBUG]: Read 2057 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2018-07-11 19:53:36,439 - util.py[DEBUG]: Attempting to load yaml from string of length 2057 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:36,443 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2018-07-11 19:53:36,443 - util.py[DEBUG]: Read 44 bytes from /run/cloud-init/cloud.cfg
2018-07-11 19:53:36,443 - util.py[DEBUG]: Attempting to load yaml from string of length 44 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:36,444 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:36,444 - util.py[DEBUG]: loaded blob returned None, returning default.
2018-07-11 19:53:36,445 - util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
2018-07-11 19:53:36,445 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
2018-07-11 19:53:36,445 - stages.py[DEBUG]: applying net config names for {'config': [{'name': 'eth0', 'mac_address': '0e:15:bc:04:d8:dc', 'subnets': [{'type': 'dhcp4'}], 'type': 'physical'}], 'version': 1}
2018-07-11 19:53:36,446 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2018-07-11 19:53:36,446 - util.py[DEBUG]: Reading from /sys/class/net/eth0/device/device (quiet=False)
2018-07-11 19:53:36,446 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2018-07-11 19:53:36,446 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2018-07-11 19:53:36,447 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2018-07-11 19:53:36,447 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2018-07-11 19:53:36,447 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2018-07-11 19:53:36,447 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2018-07-11 19:53:36,447 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2018-07-11 19:53:36,447 - util.py[DEBUG]: Reading from /sys/class/net/eth0/addr_assign_type (quiet=False)
2018-07-11 19:53:36,447 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/eth0/addr_assign_type
2018-07-11 19:53:36,447 - util.py[DEBUG]: Reading from /sys/class/net/eth0/uevent (quiet=False)
2018-07-11 19:53:36,447 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/eth0/uevent
2018-07-11 19:53:36,447 - util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
2018-07-11 19:53:36,447 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
2018-07-11 19:53:36,447 - util.py[DEBUG]: Reading from /sys/class/net/eth0/device/device (quiet=False)
2018-07-11 19:53:36,448 - util.py[DEBUG]: Reading from /sys/class/net/lo/operstate (quiet=False)
2018-07-11 19:53:36,448 - util.py[DEBUG]: Read 8 bytes from /sys/class/net/lo/operstate
2018-07-11 19:53:36,448 - util.py[DEBUG]: Reading from /sys/class/net/eth0/operstate (quiet=False)
2018-07-11 19:53:36,448 - util.py[DEBUG]: Read 3 bytes from /sys/class/net/eth0/operstate
2018-07-11 19:53:36,448 - util.py[DEBUG]: Running command ['ip', '-6', 'addr', 'show', 'permanent', 'scope', 'global'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:36,450 - util.py[DEBUG]: Running command ['ip', '-4', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:36,452 - __init__.py[DEBUG]: no work necessary for renaming of [['0e:15:bc:04:d8:dc', 'eth0', 'vif', None]]
2018-07-11 19:53:36,453 - stages.py[DEBUG]: not a new instance. network config is not applied.
2018-07-11 19:53:36,453 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/user-data.txt - wb: [600] 0 bytes
2018-07-11 19:53:36,456 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/user-data.txt.i - wb: [600] 308 bytes
2018-07-11 19:53:36,457 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/vendor-data.txt - wb: [600] 0 bytes
2018-07-11 19:53:36,458 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/vendor-data.txt.i - wb: [600] 308 bytes
2018-07-11 19:53:36,459 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2018-07-11 19:53:36,459 - util.py[DEBUG]: Read 78 bytes from /var/lib/cloud/data/set-hostname
2018-07-11 19:53:36,459 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2018-07-11 19:53:36,460 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/consume_data - wb: [644] 23 bytes
2018-07-11 19:53:36,460 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/consume_data'>)
2018-07-11 19:53:36,460 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2018-07-11 19:53:36,460 - launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
2018-07-11 19:53:36,461 - stages.py[DEBUG]: Added default handler for {'text/cloud-config', 'text/cloud-config-jsonp'} from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
2018-07-11 19:53:36,461 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2018-07-11 19:53:36,461 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2018-07-11 19:53:36,461 - stages.py[DEBUG]: Added default handler for {'text/upstart-job'} from UpstartJobPartHandler: [['text/upstart-job']]
2018-07-11 19:53:36,461 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
2018-07-11 19:53:36,461 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
2018-07-11 19:53:36,461 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
2018-07-11 19:53:36,461 - __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__begin__, None, 2) with frequency once-per-instance
2018-07-11 19:53:36,462 - __init__.py[DEBUG]: {'Content-Type': 'text/x-not-multipart', 'MIME-Version': '1.0', 'Content-Disposition': 'attachment; filename="part-001"'}
2018-07-11 19:53:36,462 - __init__.py[DEBUG]: Empty payload of type text/x-not-multipart
2018-07-11 19:53:36,462 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
2018-07-11 19:53:36,462 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
2018-07-11 19:53:36,462 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/cloud-config.txt - wb: [600] 0 bytes
2018-07-11 19:53:36,462 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
2018-07-11 19:53:36,463 - __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__end__, None, 2) with frequency once-per-instance
2018-07-11 19:53:36,463 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2018-07-11 19:53:36,463 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2018-07-11 19:53:36,463 - stages.py[DEBUG]: no vendordata from datasource
2018-07-11 19:53:36,463 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2018-07-11 19:53:36,463 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2018-07-11 19:53:36,463 - util.py[DEBUG]: Read 3101 bytes from /etc/cloud/cloud.cfg
2018-07-11 19:53:36,463 - util.py[DEBUG]: Attempting to load yaml from string of length 3101 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:36,476 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2018-07-11 19:53:36,476 - util.py[DEBUG]: Read 238 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2018-07-11 19:53:36,476 - util.py[DEBUG]: Attempting to load yaml from string of length 238 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:36,478 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2018-07-11 19:53:36,478 - util.py[DEBUG]: Read 2057 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2018-07-11 19:53:36,478 - util.py[DEBUG]: Attempting to load yaml from string of length 2057 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:36,482 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2018-07-11 19:53:36,482 - util.py[DEBUG]: Read 44 bytes from /run/cloud-init/cloud.cfg
2018-07-11 19:53:36,482 - util.py[DEBUG]: Attempting to load yaml from string of length 44 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:36,483 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:36,483 - util.py[DEBUG]: loaded blob returned None, returning default.
2018-07-11 19:53:36,483 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2018-07-11 19:53:36,483 - util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
2018-07-11 19:53:36,483 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:36,483 - util.py[DEBUG]: loaded blob returned None, returning default.
2018-07-11 19:53:36,484 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2018-07-11 19:53:36,484 - util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
2018-07-11 19:53:36,484 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2018-07-11 19:53:36,484 - util.py[DEBUG]: loaded blob returned None, returning default.
2018-07-11 19:53:36,487 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 7727 bytes
2018-07-11 19:53:36,487 - main.py[DEBUG]: used datasource 'DataSourceEc2Local' from 'Ec2' was in di_report's list: ['Ec2', 'None']
2018-07-11 19:53:36,556 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2018-07-11 19:53:36,557 - stages.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_migrator.py'>) with frequency always
2018-07-11 19:53:36,557 - handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
2018-07-11 19:53:36,557 - helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7f8a22436a90>)
2018-07-11 19:53:36,558 - cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
2018-07-11 19:53:36,558 - handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
2018-07-11 19:53:36,558 - stages.py[DEBUG]: Running module seed_random (<module 'cloudinit.config.cc_seed_random' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_seed_random.py'>) with frequency once-per-instance
2018-07-11 19:53:36,558 - handlers.py[DEBUG]: start: init-network/config-seed_random: running config-seed_random with frequency once-per-instance
2018-07-11 19:53:36,558 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_seed_random - wb: [644] 24 bytes
2018-07-11 19:53:36,559 - helpers.py[DEBUG]: Running config-seed_random using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_seed_random'>)
2018-07-11 19:53:36,559 - cc_seed_random.py[DEBUG]: no command provided
2018-07-11 19:53:36,559 - handlers.py[DEBUG]: finish: init-network/config-seed_random: SUCCESS: config-seed_random ran successfully
2018-07-11 19:53:36,559 - stages.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_bootcmd.py'>) with frequency always
2018-07-11 19:53:36,559 - handlers.py[DEBUG]: start: init-network/config-bootcmd: running config-bootcmd with frequency always
2018-07-11 19:53:36,559 - helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7f8a22436fd0>)
2018-07-11 19:53:36,559 - cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
2018-07-11 19:53:36,560 - handlers.py[DEBUG]: finish: init-network/config-bootcmd: SUCCESS: config-bootcmd ran successfully
2018-07-11 19:53:36,560 - stages.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_write_files.py'>) with frequency once-per-instance
2018-07-11 19:53:36,560 - handlers.py[DEBUG]: start: init-network/config-write-files: running config-write-files with frequency once-per-instance
2018-07-11 19:53:36,560 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_write_files - wb: [644] 23 bytes
2018-07-11 19:53:36,560 - helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_write_files'>)
2018-07-11 19:53:36,561 - cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
2018-07-11 19:53:36,561 - handlers.py[DEBUG]: finish: init-network/config-write-files: SUCCESS: config-write-files ran successfully
2018-07-11 19:53:36,561 - stages.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2018-07-11 19:53:36,561 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2018-07-11 19:53:36,561 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7f8a22432f28>)
2018-07-11 19:53:36,561 - cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'devices': ['/'], 'mode': 'auto', 'ignore_growroot_disabled': False}
2018-07-11 19:53:36,561 - util.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:36,566 - util.py[DEBUG]: Reading from /proc/830/mountinfo (quiet=False)
2018-07-11 19:53:36,566 - util.py[DEBUG]: Read 2624 bytes from /proc/830/mountinfo
2018-07-11 19:53:36,566 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:36,568 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:36,569 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:36,571 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2018-07-11 19:53:36,571 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2018-07-11 19:53:36,571 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2018-07-11 19:53:36,571 - util.py[DEBUG]: Read 932 bytes from /proc/self/status
2018-07-11 19:53:36,574 - util.py[DEBUG]: Reading from /sys/class/block/xvda1/partition (quiet=False)
2018-07-11 19:53:36,574 - util.py[DEBUG]: Read 2 bytes from /sys/class/block/xvda1/partition
2018-07-11 19:53:36,574 - util.py[DEBUG]: Reading from /sys/devices/vbd-768/block/xvda/dev (quiet=False)
2018-07-11 19:53:36,574 - util.py[DEBUG]: Read 6 bytes from /sys/devices/vbd-768/block/xvda/dev
2018-07-11 19:53:36,574 - util.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/xvda', '1'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:36,610 - util.py[DEBUG]: resize_devices took 0.044 seconds
2018-07-11 19:53:36,610 - cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/xvda, 1)
2018-07-11 19:53:36,610 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
2018-07-11 19:53:36,610 - stages.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_resizefs.py'>) with frequency always
2018-07-11 19:53:36,610 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
2018-07-11 19:53:36,611 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7f8a22432c88>)
2018-07-11 19:53:36,611 - schema.py[DEBUG]: Ignoring schema validation. python-jsonschema is not present
2018-07-11 19:53:36,611 - util.py[DEBUG]: Reading from /proc/830/mountinfo (quiet=False)
2018-07-11 19:53:36,611 - util.py[DEBUG]: Read 2624 bytes from /proc/830/mountinfo
2018-07-11 19:53:36,611 - cc_resizefs.py[DEBUG]: resize_info: dev=/dev/xvda1 mnt_point=/ path=/
2018-07-11 19:53:36,612 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:36,614 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:36,615 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:36,616 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2018-07-11 19:53:36,617 - util.py[DEBUG]: Read 150 bytes from /proc/1/environ
2018-07-11 19:53:36,617 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2018-07-11 19:53:36,617 - util.py[DEBUG]: Read 932 bytes from /proc/self/status
2018-07-11 19:53:36,617 - cc_resizefs.py[DEBUG]: Resizing / (ext4) using resize2fs /dev/xvda1
2018-07-11 19:53:36,617 - util.py[DEBUG]: Running command ('resize2fs', '/dev/xvda1') with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:36,627 - util.py[DEBUG]: Resizing took 0.010 seconds
2018-07-11 19:53:36,628 - cc_resizefs.py[DEBUG]: Resized root filesystem (type=ext4, val=True)
2018-07-11 19:53:36,628 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
2018-07-11 19:53:36,628 - stages.py[DEBUG]: Running module disk_setup (<module 'cloudinit.config.cc_disk_setup' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_disk_setup.py'>) with frequency once-per-instance
2018-07-11 19:53:36,628 - handlers.py[DEBUG]: start: init-network/config-disk_setup: running config-disk_setup with frequency once-per-instance
2018-07-11 19:53:36,629 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_disk_setup - wb: [644] 24 bytes
2018-07-11 19:53:36,629 - helpers.py[DEBUG]: Running config-disk_setup using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_disk_setup'>)
2018-07-11 19:53:36,629 - handlers.py[DEBUG]: finish: init-network/config-disk_setup: SUCCESS: config-disk_setup ran successfully
2018-07-11 19:53:36,629 - stages.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2018-07-11 19:53:36,630 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2018-07-11 19:53:36,630 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_mounts - wb: [644] 24 bytes
2018-07-11 19:53:36,630 - helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_mounts'>)
2018-07-11 19:53:36,630 - cc_mounts.py[DEBUG]: mounts configuration is []
2018-07-11 19:53:36,632 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
2018-07-11 19:53:36,633 - DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
2018-07-11 19:53:36,633 - cc_mounts.py[DEBUG]: Ignoring nonexistant default named mount ephemeral0
2018-07-11 19:53:36,633 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
2018-07-11 19:53:36,633 - DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
2018-07-11 19:53:36,633 - cc_mounts.py[DEBUG]: Ignoring nonexistant default named mount swap
2018-07-11 19:53:36,633 - cc_mounts.py[DEBUG]: no need to setup swap
2018-07-11 19:53:36,633 - cc_mounts.py[DEBUG]: No modifications to fstab needed.
2018-07-11 19:53:36,633 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts ran successfully
2018-07-11 19:53:36,633 - stages.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_set_hostname.py'>) with frequency once-per-instance
2018-07-11 19:53:36,633 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency once-per-instance
2018-07-11 19:53:36,633 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_set_hostname - wb: [644] 24 bytes
2018-07-11 19:53:36,634 - helpers.py[DEBUG]: Running config-set_hostname using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_set_hostname'>)
2018-07-11 19:53:36,634 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2018-07-11 19:53:36,634 - util.py[DEBUG]: Read 78 bytes from /var/lib/cloud/data/set-hostname
2018-07-11 19:53:36,634 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2018-07-11 19:53:36,634 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname ran successfully
2018-07-11 19:53:36,634 - stages.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always
2018-07-11 19:53:36,635 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always
2018-07-11 19:53:36,635 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f8a223e24e0>)
2018-07-11 19:53:36,635 - cc_update_hostname.py[DEBUG]: Updating hostname to ip-172-31-29-193.ec2.internal (ip-172-31-29-193)
2018-07-11 19:53:36,635 - util.py[DEBUG]: Reading from /etc/hostname (quiet=False)
2018-07-11 19:53:36,635 - util.py[DEBUG]: Read 17 bytes from /etc/hostname
2018-07-11 19:53:36,635 - __init__.py[DEBUG]: Attempting to update hostname to ip-172-31-29-193 in 1 files
2018-07-11 19:53:36,635 - util.py[DEBUG]: Reading from /var/lib/cloud/data/previous-hostname (quiet=False)
2018-07-11 19:53:36,635 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 17 bytes
2018-07-11 19:53:36,636 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully
2018-07-11 19:53:36,636 - stages.py[DEBUG]: Running module update_etc_hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_update_etc_hosts.py'>) with frequency always
2018-07-11 19:53:36,636 - handlers.py[DEBUG]: start: init-network/config-update_etc_hosts: running config-update_etc_hosts with frequency always
2018-07-11 19:53:36,636 - helpers.py[DEBUG]: Running config-update_etc_hosts using lock (<cloudinit.helpers.DummyLock object at 0x7f8a22434518>)
2018-07-11 19:53:36,636 - cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update_etc_hosts
2018-07-11 19:53:36,636 - handlers.py[DEBUG]: finish: init-network/config-update_etc_hosts: SUCCESS: config-update_etc_hosts ran successfully
2018-07-11 19:53:36,636 - stages.py[DEBUG]: Running module ca-certs (<module 'cloudinit.config.cc_ca_certs' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ca_certs.py'>) with frequency once-per-instance
2018-07-11 19:53:36,636 - handlers.py[DEBUG]: start: init-network/config-ca-certs: running config-ca-certs with frequency once-per-instance
2018-07-11 19:53:36,637 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_ca_certs - wb: [644] 24 bytes
2018-07-11 19:53:36,637 - helpers.py[DEBUG]: Running config-ca-certs using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_ca_certs'>)
2018-07-11 19:53:36,637 - cc_ca_certs.py[DEBUG]: Skipping module named ca-certs, no 'ca-certs' key in configuration
2018-07-11 19:53:36,637 - handlers.py[DEBUG]: finish: init-network/config-ca-certs: SUCCESS: config-ca-certs ran successfully
2018-07-11 19:53:36,637 - stages.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_rsyslog.py'>) with frequency once-per-instance
2018-07-11 19:53:36,637 - handlers.py[DEBUG]: start: init-network/config-rsyslog: running config-rsyslog with frequency once-per-instance
2018-07-11 19:53:36,638 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_rsyslog - wb: [644] 23 bytes
2018-07-11 19:53:36,638 - helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_rsyslog'>)
2018-07-11 19:53:36,638 - cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
2018-07-11 19:53:36,638 - handlers.py[DEBUG]: finish: init-network/config-rsyslog: SUCCESS: config-rsyslog ran successfully
2018-07-11 19:53:36,638 - stages.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2018-07-11 19:53:36,638 - handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
2018-07-11 19:53:36,639 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_users_groups - wb: [644] 24 bytes
2018-07-11 19:53:36,639 - helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_users_groups'>)
2018-07-11 19:53:36,640 - util.py[DEBUG]: Reading from /etc/os-release (quiet=True)
2018-07-11 19:53:36,640 - util.py[DEBUG]: Read 298 bytes from /etc/os-release
2018-07-11 19:53:36,640 - util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)
2018-07-11 19:53:36,640 - util.py[DEBUG]: Read 0 bytes from /etc/system-image/channel.ini
2018-07-11 19:53:36,640 - __init__.py[DEBUG]: Adding user ubuntu
2018-07-11 19:53:36,640 - util.py[DEBUG]: Running hidden command to protect sensitive input/output logstring: ['useradd', 'ubuntu', '--comment', 'Ubuntu', '--groups', 'adm,audio,cdrom,dialout,dip,floppy,lxd,netdev,plugdev,sudo,video', '--shell', '/bin/bash', '-m']
2018-07-11 19:53:36,716 - util.py[DEBUG]: Running command ['passwd', '-l', 'ubuntu'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:36,728 - util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
2018-07-11 19:53:36,729 - util.py[DEBUG]: Read 755 bytes from /etc/sudoers
2018-07-11 19:53:36,731 - util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - wb: [440] 122 bytes
2018-07-11 19:53:36,732 - handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully
2018-07-11 19:53:36,732 - stages.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2018-07-11 19:53:36,732 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2018-07-11 19:53:36,732 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_ssh - wb: [644] 24 bytes
2018-07-11 19:53:36,733 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_ssh'>)
2018-07-11 19:53:36,734 - util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'rsa', '-N', '', '-f', '/etc/ssh/ssh_host_rsa_key'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:36,789 - util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'dsa', '-N', '', '-f', '/etc/ssh/ssh_host_dsa_key'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:36,828 - util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:36,832 - util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:36,839 - util.py[DEBUG]: Changing the ownership of /home/ubuntu/.ssh to 1000:1000
2018-07-11 19:53:36,839 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2018-07-11 19:53:36,840 - util.py[DEBUG]: Read 2540 bytes from /etc/ssh/sshd_config
2018-07-11 19:53:36,841 - util.py[DEBUG]: Writing to /home/ubuntu/.ssh/authorized_keys - wb: [600] 391 bytes
2018-07-11 19:53:36,841 - util.py[DEBUG]: Changing the ownership of /home/ubuntu/.ssh/authorized_keys to 1000:1000
2018-07-11 19:53:36,842 - util.py[DEBUG]: Changing the ownership of /root/.ssh to 0:0
2018-07-11 19:53:36,842 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2018-07-11 19:53:36,842 - util.py[DEBUG]: Read 2540 bytes from /etc/ssh/sshd_config
2018-07-11 19:53:36,843 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 546 bytes
2018-07-11 19:53:36,843 - util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
2018-07-11 19:53:36,843 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully
2018-07-11 19:53:36,843 - main.py[DEBUG]: Ran 15 modules with 0 failures
2018-07-11 19:53:36,844 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2018-07-11 19:53:36,844 - util.py[DEBUG]: Read 10 bytes from /proc/uptime
2018-07-11 19:53:36,844 - util.py[DEBUG]: cloud-init mode 'init' took 0.494 seconds (0.49)
2018-07-11 19:53:36,844 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2018-07-11 19:53:38,407 - util.py[DEBUG]: Cloud-init v. 18.2 running 'modules:config' at Wed, 11 Jul 2018 19:53:38 +0000. Up 8.25 seconds.
2018-07-11 19:53:38,452 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2018-07-11 19:53:38,453 - stages.py[DEBUG]: Running module emit_upstart (<module 'cloudinit.config.cc_emit_upstart' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_emit_upstart.py'>) with frequency always
2018-07-11 19:53:38,453 - handlers.py[DEBUG]: start: modules-config/config-emit_upstart: running config-emit_upstart with frequency always
2018-07-11 19:53:38,453 - helpers.py[DEBUG]: Running config-emit_upstart using lock (<cloudinit.helpers.DummyLock object at 0x7f9a3a685710>)
2018-07-11 19:53:38,453 - cc_emit_upstart.py[DEBUG]: no /sbin/initctl located
2018-07-11 19:53:38,453 - cc_emit_upstart.py[DEBUG]: not upstart system, 'emit_upstart' disabled
2018-07-11 19:53:38,454 - handlers.py[DEBUG]: finish: modules-config/config-emit_upstart: SUCCESS: config-emit_upstart ran successfully
2018-07-11 19:53:38,454 - stages.py[DEBUG]: Running module snap (<module 'cloudinit.config.cc_snap' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_snap.py'>) with frequency once-per-instance
2018-07-11 19:53:38,454 - handlers.py[DEBUG]: start: modules-config/config-snap: running config-snap with frequency once-per-instance
2018-07-11 19:53:38,454 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_snap - wb: [644] 24 bytes
2018-07-11 19:53:38,455 - helpers.py[DEBUG]: Running config-snap using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_snap'>)
2018-07-11 19:53:38,455 - cc_snap.py[DEBUG]: Skipping module named snap, no 'snap' key in configuration
2018-07-11 19:53:38,455 - handlers.py[DEBUG]: finish: modules-config/config-snap: SUCCESS: config-snap ran successfully
2018-07-11 19:53:38,455 - stages.py[DEBUG]: Running module snap_config (<module 'cloudinit.config.cc_snap_config' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_snap_config.py'>) with frequency once-per-instance
2018-07-11 19:53:38,455 - handlers.py[DEBUG]: start: modules-config/config-snap_config: running config-snap_config with frequency once-per-instance
2018-07-11 19:53:38,455 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_snap_config - wb: [644] 24 bytes
2018-07-11 19:53:38,456 - helpers.py[DEBUG]: Running config-snap_config using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_snap_config'>)
2018-07-11 19:53:38,456 - cc_snap_config.py[DEBUG]: No snappy config provided, skipping
2018-07-11 19:53:38,456 - handlers.py[DEBUG]: finish: modules-config/config-snap_config: SUCCESS: config-snap_config ran successfully
2018-07-11 19:53:38,456 - stages.py[DEBUG]: Running module ssh-import-id (<module 'cloudinit.config.cc_ssh_import_id' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh_import_id.py'>) with frequency once-per-instance
2018-07-11 19:53:38,456 - handlers.py[DEBUG]: start: modules-config/config-ssh-import-id: running config-ssh-import-id with frequency once-per-instance
2018-07-11 19:53:38,456 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_ssh_import_id - wb: [644] 24 bytes
2018-07-11 19:53:38,457 - helpers.py[DEBUG]: Running config-ssh-import-id using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_ssh_import_id'>)
2018-07-11 19:53:38,457 - handlers.py[DEBUG]: finish: modules-config/config-ssh-import-id: SUCCESS: config-ssh-import-id ran successfully
2018-07-11 19:53:38,457 - stages.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_locale.py'>) with frequency once-per-instance
2018-07-11 19:53:38,457 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
2018-07-11 19:53:38,457 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_locale - wb: [644] 23 bytes
2018-07-11 19:53:38,458 - helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_locale'>)
2018-07-11 19:53:38,458 - util.py[DEBUG]: Reading from /etc/default/locale (quiet=False)
2018-07-11 19:53:38,458 - util.py[DEBUG]: Read 13 bytes from /etc/default/locale
2018-07-11 19:53:38,458 - cc_locale.py[DEBUG]: Setting locale to C.UTF-8
2018-07-11 19:53:38,458 - debian.py[DEBUG]: System has 'LANG=C.UTF-8' requested 'C.UTF-8', skipping regeneration.
2018-07-11 19:53:38,458 - handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully
2018-07-11 19:53:38,458 - stages.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance
2018-07-11 19:53:38,458 - handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
2018-07-11 19:53:38,459 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_set_passwords - wb: [644] 24 bytes
2018-07-11 19:53:38,459 - helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_set_passwords'>)
2018-07-11 19:53:38,459 - handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully
2018-07-11 19:53:38,459 - stages.py[DEBUG]: Running module grub-dpkg (<module 'cloudinit.config.cc_grub_dpkg' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_grub_dpkg.py'>) with frequency once-per-instance
2018-07-11 19:53:38,459 - handlers.py[DEBUG]: start: modules-config/config-grub-dpkg: running config-grub-dpkg with frequency once-per-instance
2018-07-11 19:53:38,459 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_grub_dpkg - wb: [644] 24 bytes
2018-07-11 19:53:38,460 - helpers.py[DEBUG]: Running config-grub-dpkg using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_grub_dpkg'>)
2018-07-11 19:53:38,460 - cc_grub_dpkg.py[DEBUG]: Setting grub debconf-set-selections with '/dev/xvda','false'
2018-07-11 19:53:38,460 - util.py[DEBUG]: Running command ['debconf-set-selections'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:38,640 - handlers.py[DEBUG]: finish: modules-config/config-grub-dpkg: SUCCESS: config-grub-dpkg ran successfully
2018-07-11 19:53:38,641 - stages.py[DEBUG]: Running module apt-pipelining (<module 'cloudinit.config.cc_apt_pipelining' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_apt_pipelining.py'>) with frequency once-per-instance
2018-07-11 19:53:38,641 - handlers.py[DEBUG]: start: modules-config/config-apt-pipelining: running config-apt-pipelining with frequency once-per-instance
2018-07-11 19:53:38,641 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_apt_pipelining - wb: [644] 23 bytes
2018-07-11 19:53:38,642 - helpers.py[DEBUG]: Running config-apt-pipelining using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_apt_pipelining'>)
2018-07-11 19:53:38,644 - util.py[DEBUG]: Writing to /etc/apt/apt.conf.d/90cloud-init-pipelining - wb: [644] 80 bytes
2018-07-11 19:53:38,645 - cc_apt_pipelining.py[DEBUG]: Wrote /etc/apt/apt.conf.d/90cloud-init-pipelining with apt pipeline depth setting 0
2018-07-11 19:53:38,645 - handlers.py[DEBUG]: finish: modules-config/config-apt-pipelining: SUCCESS: config-apt-pipelining ran successfully
2018-07-11 19:53:38,645 - stages.py[DEBUG]: Running module apt-configure (<module 'cloudinit.config.cc_apt_configure' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_apt_configure.py'>) with frequency once-per-instance
2018-07-11 19:53:38,646 - handlers.py[DEBUG]: start: modules-config/config-apt-configure: running config-apt-configure with frequency once-per-instance
2018-07-11 19:53:38,646 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_apt_configure - wb: [644] 24 bytes
2018-07-11 19:53:38,646 - helpers.py[DEBUG]: Running config-apt-configure using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_apt_configure'>)
2018-07-11 19:53:38,646 - cc_apt_configure.py[DEBUG]: debconf_selections was not set in config
2018-07-11 19:53:38,646 - util.py[DEBUG]: Reading from /etc/os-release (quiet=True)
2018-07-11 19:53:38,646 - util.py[DEBUG]: Read 298 bytes from /etc/os-release
2018-07-11 19:53:38,647 - util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)
2018-07-11 19:53:38,649 - util.py[DEBUG]: Read 0 bytes from /etc/system-image/channel.ini
2018-07-11 19:53:38,649 - cc_apt_configure.py[DEBUG]: handling apt config: {}
2018-07-11 19:53:38,649 - util.py[DEBUG]: Running command ['lsb_release', '--all'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:38,727 - util.py[DEBUG]: Running command ['dpkg', '--print-architecture'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:38,730 - cc_apt_configure.py[DEBUG]: got primary mirror: None
2018-07-11 19:53:38,731 - cc_apt_configure.py[DEBUG]: got security mirror: None
2018-07-11 19:53:38,731 - util.py[DEBUG]: Running command ['dpkg', '--print-architecture'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:38,760 - __init__.py[DEBUG]: filtered distro mirror info: {'security': 'http://security.ubuntu.com/ubuntu', 'primary': 'http://us-east-1.ec2.archive.ubuntu.com/ubuntu/'}
2018-07-11 19:53:38,761 - cc_apt_configure.py[DEBUG]: Apt Mirror info: {'SECURITY': 'http://security.ubuntu.com/ubuntu', 'security': 'http://security.ubuntu.com/ubuntu', 'PRIMARY': 'http://us-east-1.ec2.archive.ubuntu.com/ubuntu/', 'primary': 'http://us-east-1.ec2.archive.ubuntu.com/ubuntu/', 'MIRROR': 'http://us-east-1.ec2.archive.ubuntu.com/ubuntu/'}
2018-07-11 19:53:38,761 - cc_apt_configure.py[INFO]: No custom template provided, fall back to builtin
2018-07-11 19:53:38,761 - util.py[DEBUG]: Reading from /etc/cloud/templates/sources.list.ubuntu.tmpl (quiet=False)
2018-07-11 19:53:38,762 - util.py[DEBUG]: Read 2841 bytes from /etc/cloud/templates/sources.list.ubuntu.tmpl
2018-07-11 19:53:38,770 - util.py[DEBUG]: Writing to /etc/apt/sources.list - wb: [644] 3335 bytes
2018-07-11 19:53:38,771 - util.py[DEBUG]: Running command ['dpkg', '--print-architecture'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:38,780 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-updates_main_binary-amd64_Packages to /var/lib/apt/lists/us-east-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial-updates_main_binary-amd64_Packages
2018-07-11 19:53:38,780 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease to /var/lib/apt/lists/us-east-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease
2018-07-11 19:53:38,780 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-updates_restricted_i18n_Translation-en to /var/lib/apt/lists/us-east-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial-updates_restricted_i18n_Translation-en
2018-07-11 19:53:38,780 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_main_i18n_Translation-en to /var/lib/apt/lists/us-east-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial_main_i18n_Translation-en
2018-07-11 19:53:38,780 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_InRelease to /var/lib/apt/lists/us-east-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial_InRelease
2018-07-11 19:53:38,781 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-updates_restricted_binary-amd64_Packages to /var/lib/apt/lists/us-east-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial-updates_restricted_binary-amd64_Packages
2018-07-11 19:53:38,781 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_restricted_binary-amd64_Packages to /var/lib/apt/lists/us-east-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial_restricted_binary-amd64_Packages
2018-07-11 19:53:38,781 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_main_binary-amd64_Packages to /var/lib/apt/lists/us-east-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial_main_binary-amd64_Packages
2018-07-11 19:53:38,781 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-updates_main_i18n_Translation-en to /var/lib/apt/lists/us-east-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial-updates_main_i18n_Translation-en
2018-07-11 19:53:38,781 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_restricted_i18n_Translation-en to /var/lib/apt/lists/us-east-1.ec2.archive.ubuntu.com_ubuntu_dists_xenial_restricted_i18n_Translation-en
2018-07-11 19:53:38,781 - handlers.py[DEBUG]: finish: modules-config/config-apt-configure: SUCCESS: config-apt-configure ran successfully
2018-07-11 19:53:38,781 - stages.py[DEBUG]: Running module ubuntu-advantage (<module 'cloudinit.config.cc_ubuntu_advantage' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ubuntu_advantage.py'>) with frequency once-per-instance
2018-07-11 19:53:38,781 - handlers.py[DEBUG]: start: modules-config/config-ubuntu-advantage: running config-ubuntu-advantage with frequency once-per-instance
2018-07-11 19:53:38,782 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_ubuntu_advantage - wb: [644] 24 bytes
2018-07-11 19:53:38,782 - helpers.py[DEBUG]: Running config-ubuntu-advantage using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_ubuntu_advantage'>)
2018-07-11 19:53:38,782 - cc_ubuntu_advantage.py[DEBUG]: Skipping module named ubuntu-advantage, no 'ubuntu-advantage' key in configuration
2018-07-11 19:53:38,783 - handlers.py[DEBUG]: finish: modules-config/config-ubuntu-advantage: SUCCESS: config-ubuntu-advantage ran successfully
2018-07-11 19:53:38,783 - stages.py[DEBUG]: Running module ntp (<module 'cloudinit.config.cc_ntp' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ntp.py'>) with frequency once-per-instance
2018-07-11 19:53:38,783 - handlers.py[DEBUG]: start: modules-config/config-ntp: running config-ntp with frequency once-per-instance
2018-07-11 19:53:38,783 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_ntp - wb: [644] 24 bytes
2018-07-11 19:53:38,783 - helpers.py[DEBUG]: Running config-ntp using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_ntp'>)
2018-07-11 19:53:38,784 - cc_ntp.py[DEBUG]: Skipping module named ntp, not present or disabled by cfg
2018-07-11 19:53:38,784 - handlers.py[DEBUG]: finish: modules-config/config-ntp: SUCCESS: config-ntp ran successfully
2018-07-11 19:53:38,784 - stages.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_timezone.py'>) with frequency once-per-instance
2018-07-11 19:53:38,784 - handlers.py[DEBUG]: start: modules-config/config-timezone: running config-timezone with frequency once-per-instance
2018-07-11 19:53:38,784 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_timezone - wb: [644] 24 bytes
2018-07-11 19:53:38,784 - helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_timezone'>)
2018-07-11 19:53:38,785 - cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
2018-07-11 19:53:38,785 - handlers.py[DEBUG]: finish: modules-config/config-timezone: SUCCESS: config-timezone ran successfully
2018-07-11 19:53:38,785 - stages.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_disable_ec2_metadata.py'>) with frequency always
2018-07-11 19:53:38,785 - handlers.py[DEBUG]: start: modules-config/config-disable-ec2-metadata: running config-disable-ec2-metadata with frequency always
2018-07-11 19:53:38,785 - helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7f9a39e90cf8>)
2018-07-11 19:53:38,785 - cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
2018-07-11 19:53:38,785 - handlers.py[DEBUG]: finish: modules-config/config-disable-ec2-metadata: SUCCESS: config-disable-ec2-metadata ran successfully
2018-07-11 19:53:38,785 - stages.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_runcmd.py'>) with frequency once-per-instance
2018-07-11 19:53:38,785 - handlers.py[DEBUG]: start: modules-config/config-runcmd: running config-runcmd with frequency once-per-instance
2018-07-11 19:53:38,786 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_runcmd - wb: [644] 23 bytes
2018-07-11 19:53:38,786 - helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_runcmd'>)
2018-07-11 19:53:38,786 - cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
2018-07-11 19:53:38,786 - handlers.py[DEBUG]: finish: modules-config/config-runcmd: SUCCESS: config-runcmd ran successfully
2018-07-11 19:53:38,786 - stages.py[DEBUG]: Running module byobu (<module 'cloudinit.config.cc_byobu' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_byobu.py'>) with frequency once-per-instance
2018-07-11 19:53:38,786 - handlers.py[DEBUG]: start: modules-config/config-byobu: running config-byobu with frequency once-per-instance
2018-07-11 19:53:38,787 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_byobu - wb: [644] 24 bytes
2018-07-11 19:53:38,791 - helpers.py[DEBUG]: Running config-byobu using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_byobu'>)
2018-07-11 19:53:38,791 - cc_byobu.py[DEBUG]: Skipping module named byobu, no 'byobu' values found
2018-07-11 19:53:38,791 - handlers.py[DEBUG]: finish: modules-config/config-byobu: SUCCESS: config-byobu ran successfully
2018-07-11 19:53:38,791 - main.py[DEBUG]: Ran 15 modules with 0 failures
2018-07-11 19:53:38,792 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2018-07-11 19:53:38,792 - util.py[DEBUG]: Read 10 bytes from /proc/uptime
2018-07-11 19:53:38,792 - util.py[DEBUG]: cloud-init mode 'modules' took 0.532 seconds (0.53)
2018-07-11 19:53:38,792 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2018-07-11 19:53:46,319 - util.py[DEBUG]: Cloud-init v. 18.2 running 'modules:final' at Wed, 11 Jul 2018 19:53:46 +0000. Up 16.18 seconds.
2018-07-11 19:53:46,444 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2018-07-11 19:53:46,445 - stages.py[DEBUG]: Running module snappy (<module 'cloudinit.config.cc_snappy' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_snappy.py'>) with frequency once-per-instance
2018-07-11 19:53:46,445 - handlers.py[DEBUG]: start: modules-final/config-snappy: running config-snappy with frequency once-per-instance
2018-07-11 19:53:46,446 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_snappy - wb: [644] 25 bytes
2018-07-11 19:53:46,446 - helpers.py[DEBUG]: Running config-snappy using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_snappy'>)
2018-07-11 19:53:46,446 - util.py[DEBUG]: Reading from /etc/os-release (quiet=True)
2018-07-11 19:53:46,446 - util.py[DEBUG]: Read 298 bytes from /etc/os-release
2018-07-11 19:53:46,449 - util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)
2018-07-11 19:53:46,449 - util.py[DEBUG]: Read 0 bytes from /etc/system-image/channel.ini
2018-07-11 19:53:46,450 - cc_snappy.py[DEBUG]: snappy: 'auto' mode, and system not snappy
2018-07-11 19:53:46,450 - handlers.py[DEBUG]: finish: modules-final/config-snappy: SUCCESS: config-snappy ran successfully
2018-07-11 19:53:46,450 - stages.py[DEBUG]: Running module package-update-upgrade-install (<module 'cloudinit.config.cc_package_update_upgrade_install' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py'>) with frequency once-per-instance
2018-07-11 19:53:46,450 - handlers.py[DEBUG]: start: modules-final/config-package-update-upgrade-install: running config-package-update-upgrade-install with frequency once-per-instance
2018-07-11 19:53:46,451 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_package_update_upgrade_install - wb: [644] 25 bytes
2018-07-11 19:53:46,453 - helpers.py[DEBUG]: Running config-package-update-upgrade-install using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_package_update_upgrade_install'>)
2018-07-11 19:53:46,453 - handlers.py[DEBUG]: finish: modules-final/config-package-update-upgrade-install: SUCCESS: config-package-update-upgrade-install ran successfully
2018-07-11 19:53:46,453 - stages.py[DEBUG]: Running module fan (<module 'cloudinit.config.cc_fan' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_fan.py'>) with frequency once-per-instance
2018-07-11 19:53:46,454 - handlers.py[DEBUG]: start: modules-final/config-fan: running config-fan with frequency once-per-instance
2018-07-11 19:53:46,454 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_fan - wb: [644] 25 bytes
2018-07-11 19:53:46,454 - helpers.py[DEBUG]: Running config-fan using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_fan'>)
2018-07-11 19:53:46,454 - cc_fan.py[DEBUG]: fan: no 'fan' config entry. disabling
2018-07-11 19:53:46,454 - handlers.py[DEBUG]: finish: modules-final/config-fan: SUCCESS: config-fan ran successfully
2018-07-11 19:53:46,455 - stages.py[DEBUG]: Running module landscape (<module 'cloudinit.config.cc_landscape' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_landscape.py'>) with frequency once-per-instance
2018-07-11 19:53:46,455 - handlers.py[DEBUG]: start: modules-final/config-landscape: running config-landscape with frequency once-per-instance
2018-07-11 19:53:46,459 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_landscape - wb: [644] 25 bytes
2018-07-11 19:53:46,460 - helpers.py[DEBUG]: Running config-landscape using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_landscape'>)
2018-07-11 19:53:46,460 - handlers.py[DEBUG]: finish: modules-final/config-landscape: SUCCESS: config-landscape ran successfully
2018-07-11 19:53:46,460 - stages.py[DEBUG]: Running module lxd (<module 'cloudinit.config.cc_lxd' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_lxd.py'>) with frequency once-per-instance
2018-07-11 19:53:46,460 - handlers.py[DEBUG]: start: modules-final/config-lxd: running config-lxd with frequency once-per-instance
2018-07-11 19:53:46,460 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_lxd - wb: [644] 24 bytes
2018-07-11 19:53:46,461 - helpers.py[DEBUG]: Running config-lxd using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_lxd'>)
2018-07-11 19:53:46,461 - cc_lxd.py[DEBUG]: Skipping module named lxd, not present or disabled by cfg
2018-07-11 19:53:46,461 - handlers.py[DEBUG]: finish: modules-final/config-lxd: SUCCESS: config-lxd ran successfully
2018-07-11 19:53:46,461 - stages.py[DEBUG]: Running module puppet (<module 'cloudinit.config.cc_puppet' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_puppet.py'>) with frequency once-per-instance
2018-07-11 19:53:46,461 - handlers.py[DEBUG]: start: modules-final/config-puppet: running config-puppet with frequency once-per-instance
2018-07-11 19:53:46,461 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_puppet - wb: [644] 24 bytes
2018-07-11 19:53:46,462 - helpers.py[DEBUG]: Running config-puppet using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_puppet'>)
2018-07-11 19:53:46,462 - cc_puppet.py[DEBUG]: Skipping module named puppet, no 'puppet' configuration found
2018-07-11 19:53:46,462 - handlers.py[DEBUG]: finish: modules-final/config-puppet: SUCCESS: config-puppet ran successfully
2018-07-11 19:53:46,462 - stages.py[DEBUG]: Running module chef (<module 'cloudinit.config.cc_chef' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_chef.py'>) with frequency once-per-instance
2018-07-11 19:53:46,462 - handlers.py[DEBUG]: start: modules-final/config-chef: running config-chef with frequency once-per-instance
2018-07-11 19:53:46,462 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_chef - wb: [644] 25 bytes
2018-07-11 19:53:46,463 - helpers.py[DEBUG]: Running config-chef using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_chef'>)
2018-07-11 19:53:46,463 - cc_chef.py[DEBUG]: Skipping module named chef, no 'chef' key in configuration
2018-07-11 19:53:46,463 - handlers.py[DEBUG]: finish: modules-final/config-chef: SUCCESS: config-chef ran successfully
2018-07-11 19:53:46,463 - stages.py[DEBUG]: Running module mcollective (<module 'cloudinit.config.cc_mcollective' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_mcollective.py'>) with frequency once-per-instance
2018-07-11 19:53:46,467 - handlers.py[DEBUG]: start: modules-final/config-mcollective: running config-mcollective with frequency once-per-instance
2018-07-11 19:53:46,467 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_mcollective - wb: [644] 25 bytes
2018-07-11 19:53:46,468 - helpers.py[DEBUG]: Running config-mcollective using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_mcollective'>)
2018-07-11 19:53:46,468 - cc_mcollective.py[DEBUG]: Skipping module named mcollective, no 'mcollective' key in configuration
2018-07-11 19:53:46,468 - handlers.py[DEBUG]: finish: modules-final/config-mcollective: SUCCESS: config-mcollective ran successfully
2018-07-11 19:53:46,468 - stages.py[DEBUG]: Running module salt-minion (<module 'cloudinit.config.cc_salt_minion' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_salt_minion.py'>) with frequency once-per-instance
2018-07-11 19:53:46,468 - handlers.py[DEBUG]: start: modules-final/config-salt-minion: running config-salt-minion with frequency once-per-instance
2018-07-11 19:53:46,468 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_salt_minion - wb: [644] 24 bytes
2018-07-11 19:53:46,469 - helpers.py[DEBUG]: Running config-salt-minion using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_salt_minion'>)
2018-07-11 19:53:46,469 - cc_salt_minion.py[DEBUG]: Skipping module named salt-minion, no 'salt_minion' key in configuration
2018-07-11 19:53:46,469 - handlers.py[DEBUG]: finish: modules-final/config-salt-minion: SUCCESS: config-salt-minion ran successfully
2018-07-11 19:53:46,469 - stages.py[DEBUG]: Running module rightscale_userdata (<module 'cloudinit.config.cc_rightscale_userdata' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_rightscale_userdata.py'>) with frequency once-per-instance
2018-07-11 19:53:46,469 - handlers.py[DEBUG]: start: modules-final/config-rightscale_userdata: running config-rightscale_userdata with frequency once-per-instance
2018-07-11 19:53:46,469 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_rightscale_userdata - wb: [644] 25 bytes
2018-07-11 19:53:46,470 - helpers.py[DEBUG]: Running config-rightscale_userdata using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_rightscale_userdata'>)
2018-07-11 19:53:46,470 - cc_rightscale_userdata.py[DEBUG]: Failed to get raw userdata in module rightscale_userdata
2018-07-11 19:53:46,470 - handlers.py[DEBUG]: finish: modules-final/config-rightscale_userdata: SUCCESS: config-rightscale_userdata ran successfully
2018-07-11 19:53:46,470 - stages.py[DEBUG]: Running module scripts-vendor (<module 'cloudinit.config.cc_scripts_vendor' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_vendor.py'>) with frequency once-per-instance
2018-07-11 19:53:46,470 - handlers.py[DEBUG]: start: modules-final/config-scripts-vendor: running config-scripts-vendor with frequency once-per-instance
2018-07-11 19:53:46,470 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_scripts_vendor - wb: [644] 25 bytes
2018-07-11 19:53:46,471 - helpers.py[DEBUG]: Running config-scripts-vendor using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_scripts_vendor'>)
2018-07-11 19:53:46,474 - handlers.py[DEBUG]: finish: modules-final/config-scripts-vendor: SUCCESS: config-scripts-vendor ran successfully
2018-07-11 19:53:46,474 - stages.py[DEBUG]: Running module scripts-per-once (<module 'cloudinit.config.cc_scripts_per_once' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_once.py'>) with frequency once
2018-07-11 19:53:46,474 - handlers.py[DEBUG]: start: modules-final/config-scripts-per-once: running config-scripts-per-once with frequency once
2018-07-11 19:53:46,474 - util.py[DEBUG]: Writing to /var/lib/cloud/sem/config_scripts_per_once.once - wb: [644] 25 bytes
2018-07-11 19:53:46,475 - helpers.py[DEBUG]: Running config-scripts-per-once using lock (<FileLock using file '/var/lib/cloud/sem/config_scripts_per_once.once'>)
2018-07-11 19:53:46,475 - handlers.py[DEBUG]: finish: modules-final/config-scripts-per-once: SUCCESS: config-scripts-per-once ran successfully
2018-07-11 19:53:46,476 - stages.py[DEBUG]: Running module scripts-per-boot (<module 'cloudinit.config.cc_scripts_per_boot' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_boot.py'>) with frequency always
2018-07-11 19:53:46,476 - handlers.py[DEBUG]: start: modules-final/config-scripts-per-boot: running config-scripts-per-boot with frequency always
2018-07-11 19:53:46,476 - helpers.py[DEBUG]: Running config-scripts-per-boot using lock (<cloudinit.helpers.DummyLock object at 0x7f4f1251ebe0>)
2018-07-11 19:53:46,476 - handlers.py[DEBUG]: finish: modules-final/config-scripts-per-boot: SUCCESS: config-scripts-per-boot ran successfully
2018-07-11 19:53:46,476 - stages.py[DEBUG]: Running module scripts-per-instance (<module 'cloudinit.config.cc_scripts_per_instance' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_instance.py'>) with frequency once-per-instance
2018-07-11 19:53:46,476 - handlers.py[DEBUG]: start: modules-final/config-scripts-per-instance: running config-scripts-per-instance with frequency once-per-instance
2018-07-11 19:53:46,476 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_scripts_per_instance - wb: [644] 25 bytes
2018-07-11 19:53:46,477 - helpers.py[DEBUG]: Running config-scripts-per-instance using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_scripts_per_instance'>)
2018-07-11 19:53:46,477 - handlers.py[DEBUG]: finish: modules-final/config-scripts-per-instance: SUCCESS: config-scripts-per-instance ran successfully
2018-07-11 19:53:46,477 - stages.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) with frequency once-per-instance
2018-07-11 19:53:46,477 - handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency once-per-instance
2018-07-11 19:53:46,477 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_scripts_user - wb: [644] 25 bytes
2018-07-11 19:53:46,478 - helpers.py[DEBUG]: Running config-scripts-user using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_scripts_user'>)
2018-07-11 19:53:46,478 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user ran successfully
2018-07-11 19:53:46,478 - stages.py[DEBUG]: Running module ssh-authkey-fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh_authkey_fingerprints.py'>) with frequency once-per-instance
2018-07-11 19:53:46,478 - handlers.py[DEBUG]: start: modules-final/config-ssh-authkey-fingerprints: running config-ssh-authkey-fingerprints with frequency once-per-instance
2018-07-11 19:53:46,478 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_ssh_authkey_fingerprints - wb: [644] 25 bytes
2018-07-11 19:53:46,479 - helpers.py[DEBUG]: Running config-ssh-authkey-fingerprints using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_ssh_authkey_fingerprints'>)
2018-07-11 19:53:46,483 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2018-07-11 19:53:46,483 - util.py[DEBUG]: Read 2540 bytes from /etc/ssh/sshd_config
2018-07-11 19:53:46,484 - util.py[DEBUG]: Reading from /home/ubuntu/.ssh/authorized_keys (quiet=False)
2018-07-11 19:53:46,484 - util.py[DEBUG]: Read 391 bytes from /home/ubuntu/.ssh/authorized_keys
2018-07-11 19:53:46,543 - handlers.py[DEBUG]: finish: modules-final/config-ssh-authkey-fingerprints: SUCCESS: config-ssh-authkey-fingerprints ran successfully
2018-07-11 19:53:46,543 - stages.py[DEBUG]: Running module keys-to-console (<module 'cloudinit.config.cc_keys_to_console' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_keys_to_console.py'>) with frequency once-per-instance
2018-07-11 19:53:46,544 - handlers.py[DEBUG]: start: modules-final/config-keys-to-console: running config-keys-to-console with frequency once-per-instance
2018-07-11 19:53:46,544 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_keys_to_console - wb: [644] 25 bytes
2018-07-11 19:53:46,544 - helpers.py[DEBUG]: Running config-keys-to-console using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_keys_to_console'>)
2018-07-11 19:53:46,545 - util.py[DEBUG]: Running command ['/usr/lib/cloud-init/write-ssh-key-fingerprints', '', 'ssh-dss'] with allowed return codes [0] (shell=False, capture=True)
2018-07-11 19:53:46,639 - handlers.py[DEBUG]: finish: modules-final/config-keys-to-console: SUCCESS: config-keys-to-console ran successfully
2018-07-11 19:53:46,640 - stages.py[DEBUG]: Running module phone-home (<module 'cloudinit.config.cc_phone_home' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_phone_home.py'>) with frequency once-per-instance
2018-07-11 19:53:46,640 - handlers.py[DEBUG]: start: modules-final/config-phone-home: running config-phone-home with frequency once-per-instance
2018-07-11 19:53:46,640 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_phone_home - wb: [644] 25 bytes
2018-07-11 19:53:46,641 - helpers.py[DEBUG]: Running config-phone-home using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_phone_home'>)
2018-07-11 19:53:46,641 - cc_phone_home.py[DEBUG]: Skipping module named phone-home, no 'phone_home' configuration found
2018-07-11 19:53:46,641 - handlers.py[DEBUG]: finish: modules-final/config-phone-home: SUCCESS: config-phone-home ran successfully
2018-07-11 19:53:46,641 - stages.py[DEBUG]: Running module final-message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_final_message.py'>) with frequency always
2018-07-11 19:53:46,641 - handlers.py[DEBUG]: start: modules-final/config-final-message: running config-final-message with frequency always
2018-07-11 19:53:46,642 - helpers.py[DEBUG]: Running config-final-message using lock (<cloudinit.helpers.DummyLock object at 0x7f4f11d0edd8>)
2018-07-11 19:53:46,642 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2018-07-11 19:53:46,642 - util.py[DEBUG]: Read 11 bytes from /proc/uptime
2018-07-11 19:53:46,645 - util.py[DEBUG]: Cloud-init v. 18.2 finished at Wed, 11 Jul 2018 19:53:46 +0000. Datasource DataSourceEc2Local.  Up 16.63 seconds
2018-07-11 19:53:46,645 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 50 bytes
2018-07-11 19:53:46,646 - handlers.py[DEBUG]: finish: modules-final/config-final-message: SUCCESS: config-final-message ran successfully
2018-07-11 19:53:46,646 - stages.py[DEBUG]: Running module power-state-change (<module 'cloudinit.config.cc_power_state_change' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_power_state_change.py'>) with frequency once-per-instance
2018-07-11 19:53:46,646 - handlers.py[DEBUG]: start: modules-final/config-power-state-change: running config-power-state-change with frequency once-per-instance
2018-07-11 19:53:46,646 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_power_state_change - wb: [644] 25 bytes
2018-07-11 19:53:46,647 - helpers.py[DEBUG]: Running config-power-state-change using lock (<FileLock using file '/var/lib/cloud/instances/i-0468a2b9718fc5626/sem/config_power_state_change'>)
2018-07-11 19:53:46,647 - cc_power_state_change.py[DEBUG]: no power_state provided. doing nothing
2018-07-11 19:53:46,647 - handlers.py[DEBUG]: finish: modules-final/config-power-state-change: SUCCESS: config-power-state-change ran successfully
2018-07-11 19:53:46,647 - main.py[DEBUG]: Ran 20 modules with 0 failures
2018-07-11 19:53:46,648 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2018-07-11 19:53:46,648 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2018-07-11 19:53:46,648 - util.py[DEBUG]: Read 11 bytes from /proc/uptime
2018-07-11 19:53:46,648 - util.py[DEBUG]: cloud-init mode 'modules' took 0.457 seconds (0.46)
2018-07-11 19:53:46,648 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
